openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /caps/{id}:
    get:
      tags:
      - bottle-cap-controller
      operationId: getBottleCap
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BottleCapDto"
    put:
      tags:
      - bottle-cap-controller
      operationId: updateCap
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: newName
        in: query
        required: true
        schema:
          type: string
      - name: newDesc
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BottleCapDto"
    delete:
      tags:
      - bottle-cap-controller
      operationId: deleteBottleCap
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/v1/collections/{collectionKey}/items/{id}:
    get:
      tags:
      - collection-item-controller
      operationId: getItem
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CollectionItemResponse"
    put:
      tags:
      - collection-item-controller
      operationId: updateItem
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCollectionItem"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CollectionItemResponse"
    delete:
      tags:
      - collection-item-controller
      operationId: deleteItem
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /api/v1/collections/{collectionKey}/items/{id}/image:
    put:
      tags:
      - collection-item-controller
      operationId: updateImage
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CollectionItemResponse"
  /whatCapAreYou:
    post:
      tags:
      - bottle-cap-controller
      operationId: whatCapAreYou
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      - name: file
        in: query
        required: true
        schema:
          type: string
          format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BottleCapDto"
  /validateCap:
    post:
      tags:
      - bottle-cap-controller
      operationId: validateBottleCap
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      - name: file
        in: query
        required: true
        schema:
          type: string
          format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BottleCapValidationResponseDto"
  /caps:
    get:
      tags:
      - bottle-cap-controller
      operationId: getBottleCaps
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BottleCapDto"
    post:
      tags:
      - bottle-cap-controller
      operationId: addBottleCap
      parameters:
      - name: name
        in: query
        required: true
        schema:
          type: string
      - name: desc
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/v1/collections/{collectionKey}/items:
    get:
      tags:
      - collection-item-controller
      operationId: getItems
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      - name: query
        in: query
        required: false
        schema:
          type: string
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageCollectionItemSummary"
    post:
      tags:
      - collection-item-controller
      operationId: createItem
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                request:
                  $ref: "#/components/schemas/CreateCollectionItemRequest"
              required:
              - file
              - request
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CollectionItemResponse"
  /api/v1/collections/{collectionKey}/items/validate:
    post:
      tags:
      - collection-item-controller
      operationId: validateItem
      parameters:
      - name: collectionKey
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ValidateItemResponse"
  /links:
    get:
      tags:
      - bottle-cap-controller
      operationId: getBottleCapsLinks
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CapPictureDto"
  /links-page/:
    get:
      tags:
      - bottle-cap-controller
      operationId: loadBottleCapsPage
      parameters:
      - name: pageNo
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      - name: sortBy
        in: query
        required: false
        schema:
          type: string
          default: id
      - name: sortDir
        in: query
        required: false
        schema:
          type: string
          default: asc
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CapPictureDto"
  /caps/total:
    get:
      tags:
      - bottle-cap-controller
      operationId: getCapAmount
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
  /caps-page:
    get:
      tags:
      - bottle-cap-controller
      operationId: getBottleCapsPage
      parameters:
      - name: pageNo
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      - name: sortBy
        in: query
        required: false
        schema:
          type: string
          default: id
      - name: sortDir
        in: query
        required: false
        schema:
          type: string
          default: asc
      - name: searchText
        in: query
        required: false
        schema:
          type: string
          default: ""
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BottleCapDto"
  /api/v1/public/items:
    get:
      tags:
      - public-collection-controller
      operationId: getItems_1
      parameters:
      - name: query
        in: query
        required: false
        schema:
          type: string
      - name: pageable
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/Pageable"
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageCollectionItemSummary"
  /api/v1/public/items/{id}:
    get:
      tags:
      - public-collection-controller
      operationId: getItem_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CollectionItemResponse"
  /api/v1/collections:
    get:
      tags:
      - collection-item-controller
      operationId: getUserCollections
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserCollectionResponse"
components:
  schemas:
    BottleCapDto:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        name:
          type: string
        description:
          type: string
        creationDate:
          type: string
    UpdateCollectionItem:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        customTags:
          type: object
          additionalProperties:
            type: string
    CollectionItemResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        image:
          $ref: "#/components/schemas/ImageResponse"
        visionMetadata:
          $ref: "#/components/schemas/ImageAnalysisMetadataResponse"
        tags:
          type: array
          items:
            type: string
        customTags:
          type: object
          additionalProperties:
            type: string
        userId:
          type: string
        collectionKey:
          type: string
        collectionName:
          type: string
    ImageAnalysisMetadataResponse:
      type: object
      properties:
        labels:
          type: array
          items:
            $ref: "#/components/schemas/VisionLabelDto"
        dominantColors:
          type: array
          items:
            $ref: "#/components/schemas/VisionColorDto"
        textAnnotation:
          $ref: "#/components/schemas/VisionTextDto"
        logoAnnotation:
          $ref: "#/components/schemas/VisionLogoDto"
        overallConfidence:
          type: number
          format: double
        analyzedAt:
          type: string
          format: date-time
    ImageResponse:
      type: object
      properties:
        objectName:
          type: string
        contentType:
          type: string
        sizeBytes:
          type: integer
          format: int64
        md5Hash:
          type: string
        width:
          type: integer
          format: int32
        height:
          type: integer
          format: int32
        uploadedAt:
          type: string
          format: date-time
        signedUrl:
          type: string
    VisionColorDto:
      type: object
      properties:
        red:
          type: integer
          format: int32
        green:
          type: integer
          format: int32
        blue:
          type: integer
          format: int32
        score:
          type: number
          format: double
        pixelFraction:
          type: number
          format: double
    VisionLabelDto:
      type: object
      properties:
        description:
          type: string
        score:
          type: number
          format: double
        topicality:
          type: number
          format: double
    VisionLogoDto:
      type: object
      properties:
        description:
          type: string
        score:
          type: number
          format: double
    VisionTextDto:
      type: object
      properties:
        fullText:
          type: string
        words:
          type: array
          items:
            type: string
        language:
          type: string
    BottleCapValidationResponseDto:
      type: object
      properties:
        similarCapsIDs:
          type: array
          items:
            type: string
        similarCapsURLs:
          type: array
          items:
            type: string
        similarityDistribution:
          type: array
          items:
            type: integer
            format: int32
        duplicate:
          type: boolean
    CreateCollectionItemRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        customTags:
          type: object
          additionalProperties:
            type: string
        collectionName:
          type: string
      required:
      - name
    SimilarItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        imageUrl:
          type: string
        similarityScore:
          type: number
          format: double
    ValidateItemResponse:
      type: object
      properties:
        similarCaps:
          type: array
          items:
            $ref: "#/components/schemas/SimilarItem"
        hasSimilarItems:
          type: boolean
    CapPictureDto:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
    Pageable:
      type: object
      properties:
        page:
          type: integer
          format: int32
          minimum: 0
        size:
          type: integer
          format: int32
          minimum: 1
        sort:
          type: array
          items:
            type: string
    CollectionItemSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        signedUrl:
          type: string
        collectionKey:
          type: string
        collectionName:
          type: string
        objectName:
          type: string
        customTags:
          type: object
          additionalProperties:
            type: string
    PageCollectionItemSummary:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/CollectionItemSummary"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        first:
          type: boolean
        last:
          type: boolean
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: "#/components/schemas/SortObject"
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        unpaged:
          type: boolean
        paged:
          type: boolean
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        unsorted:
          type: boolean
        sorted:
          type: boolean
    UserCollectionResponse:
      type: object
      properties:
        collectionKey:
          type: string
        collectionName:
          type: string
